server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: multiplications
        uri: lb://multiplication/multiplications
        predicates:
        - Path=/api/multiplications/**
        filters:
        - StripPrefix=1
        - name: CircuitBreaker
          args:
            name: multiplicationsCircuitBreaker
            fallbackUri: forward:/multiplications-fallback
      - id: results
        uri: lb://multiplication/results
        predicates:
        - Path=/api/results/**
        filters:
        - StripPrefix=1
      - id: leaders
        uri: lb://gamification/leaders
        predicates:
        - Path=/api/leaders/**
        filters:
        - StripPrefix=1
      - id: stats
        uri: lb://gamification/stats
        predicates:
        - Path=/api/stats/**
        filters:
        - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: httptrace, gateway
eureka:
  client:
    service-url:
      default-zone: http//localhost:8761/eureka
